name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: yarn install
    - name: Run tests
      run: yarn ci
